---

- name: install RHEL Workstation packages
  dnf:
    name: '@Workstation'
    state: present

- name: download Google Chrome RPM file
  get_url:
     url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
     dest: /tmp/google-chrome-stable_x86_64.rpm

- name: install Google Chrome from RPM
  dnf:
     name: /tmp/google-chrome-stable_x86_64.rpm
     state: present

- name: Configure GDM
  ini_file:
    path: /etc/gdm/custom.conf
    section: "{{ item.section }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
     - { section: daemon, key: AutomaticLoginEnable, value: "true" }
     - { section: daemon, key: AutomaticLogin, value: "vagrant" }
     - { section: daemon, key: WaylandEnable, value: "true" }

- name: Change default boot to graphical runlevel
  shell: "systemctl set-default graphical.target"

- name: Start graphical Desktop session
  shell: "systemctl isolate graphical.target"

- name: Restart GDM
  shell: "systemctl restart gdm.service"
